import os
from pathlib import Path
import requests
from bs4 import BeautifulSoup

# "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2313803"
autor = [
    # Adicione aqui os links das páginas
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2506856",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2494370",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2482440",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2534749",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2519925",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2525079",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2508543",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2508745",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2510632",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2532058",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2531911",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2506963",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2536177",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2501098",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2503110",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2496396",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2486276",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2490662",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2487714",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2490306",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2485575",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2485574",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2485576",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2485595",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2485981",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2485980",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2484269",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2484144",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2483805",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2483175",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2483180",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2483182",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2482267",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2467817",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2469516",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2451124",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2455855",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2453946",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2472041",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2467926",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2459090",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2467851",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2464432",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2419125",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2370111",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2374509",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2349823",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2346875",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2347270",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2352341",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2305390",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2305389",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2305388",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2313803",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2333943",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2313805",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2431085",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2302630",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2330935",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2325994",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2353792",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2297971",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2345719",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2345721",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2346876",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2325935",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2433407",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2386166",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2342042",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2222769",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2236844",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2399228",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2399229",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2407969",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2407967",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2403248",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2326167",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2419015",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2419016",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2422681",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2436591",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2432687",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2433397",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2336507",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2336276",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2418617",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2381013",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2381015",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2338659",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2339699",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2443669",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2386622",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2386624",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2385816",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2392841",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2383261",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2382670",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2382666",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2336928",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2392673",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2382767",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2330442",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2403111",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2403114",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2403102",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2412075",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2374374",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2372006",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2348390",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2374232",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2353626",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2353330",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2353003",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2358185",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2356218",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2350378",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2350539",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2355041",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2356495",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2370163",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2347129",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2375021",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2375585",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2355359",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2351475",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2366631",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2366626",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2366627",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2366169",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2362338",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2297448",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2295139",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2350517",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2346935",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2346937",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2346942",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2348960",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2348975",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2370467",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2419194",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2426803",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2427750",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2431028",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2446617",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2348959",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2295178",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2295135",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2431029",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2391397",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2415560",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2300635",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2300634",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2315094",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2314960",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2318231",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2318230",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2318229",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2318368",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2319995",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2300687",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2302653",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2305602",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2306596",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2307029",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2293872",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2303867",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2308074",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2295137",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2301141",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2314961",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2346940",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2319201",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2348385",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2349010",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2363893",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2353883",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2403101",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2375320",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2317939",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2319202",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2422677",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2410365",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2349172",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2374956",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2376168",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2392774",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2392870",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2293861",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2318936",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2410357",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2422679",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2306914",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2332879",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2438833",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2418616",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2353623",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2353631",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2335859",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2336503",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2336505",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2336504",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2336766",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2336765",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2336929",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2341927",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2426793",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2443767",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2346932",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2330933",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2307683",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2420213",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2227770",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2280974",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2241758",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2190883",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2241759",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2283099",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2277481",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2229402",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2229403",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2231559",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2225018",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2224961",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2235923",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2288249",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2248300",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2291311",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2291318",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2291321",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2222775",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2262172",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2286389",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2264601",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2268942",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2275583",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2275546",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2275542",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2289824",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2289939",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2289937",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2289819",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2260486",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2262088",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2270313",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2272125",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2194907",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2192603",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2192606",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2192754",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2236835",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2190471",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2190473",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2190472",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2236953",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2241743",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2241751",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2241748",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2241755",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2241757",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2201585",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2197051",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2237078",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2237077",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2289863",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2192604",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2291319",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2225017",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2266495",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2268943",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2268954",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2236951",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2228394",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2196620",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2260804",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2228734",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2241749",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2241754",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2241756",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2268967",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2241747",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2241745",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2241750",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2241752",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2259765",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2275549",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2241744",
]

coautores = [
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2360727",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2360726",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2360731",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2360730",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2360734",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2360732",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2371416",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2365362",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2419071",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2362097",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2487390",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2356012",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2401826",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2360722",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2360729",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2360728",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2360733",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2190752",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2478427",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2388029",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2266845",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2424865",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2529111",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2383411",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2483604",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2351620",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2467670",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2491061",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2420532",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2405983",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2351680",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2391567",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2471383",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2197199",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2317563",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2419066",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2404706",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2428346",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2497080",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2380340",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2194380",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2402861",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2518800",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2301088",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2336481",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2282791",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2431026",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2377705",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2205645",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2267019",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2321122",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2482843",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2436937",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2270314",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2346884",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2347059",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2376169",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2435230",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2430409",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2456003",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2408771",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2346931",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2241746",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2248211",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2241753",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2482983",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2346944",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2355229",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2435229",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2435228",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2458742",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2352001",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2483164",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2329063",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2486555",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2437509",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2431027",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2431025",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2368688",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2401109",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2362478",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2252649",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2350568",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2406638",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2482788",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2376477",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2336170",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2340746",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2483076",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2291133",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2448732",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2487249",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2482163",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2304959",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2482427",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2421145",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2485604",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2285501",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2504516",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2207516",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2242821",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2479738",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2363434",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2239119",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2238009",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2263670",
    "http://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2420536",
]


# headers = {"User-Agent": "Mozilla/5.0"}


def baixar_pdf(list_url, output_dir, headers=None):
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    default_headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
        "(KHTML, like Gecko) Chrome/120.0 Safari/537.36"
    }

    for url in list_url:
        try:
            resp = requests.get(url, headers=headers or default_headers, timeout=10)
            resp.raise_for_status()
            soup = BeautifulSoup(resp.content, "html.parser")

            link_tag = soup.find("a", class_="linkDownloadTeor")
            name_tag = soup.find(class_="nomeProposicao")

            if link_tag and link_tag.has_attr("href") and name_tag:
                pdf_url = link_tag["href"]
                if not pdf_url.lower().startswith("http"):
                    pdf_url = requests.compat.urljoin(url, pdf_url)

                filename = name_tag.get_text(strip=True).replace("/", "-") + ".pdf"
                filepath = output_dir / filename

                if filepath.exists():
                    print(f"⏭️ Já existe: {filepath}")
                    continue

                pdf_resp = requests.get(
                    pdf_url, headers=headers or default_headers, timeout=15
                )
                pdf_resp.raise_for_status()

                with open(filepath, "wb") as f:
                    f.write(pdf_resp.content)

                print(f"✅ Baixado: {filepath}")

            else:
                print(
                    f"⚠️ Link 'linkDownloadTeor' ou nome 'nomeProposicao' não encontrado em {url}"
                )

        except Exception as e:
            print(f"❌ Erro ao processar {url}: {e}")


print("Baixando PDFs de Leis autorais...")
output_dir1 = "./content/autorais"
baixar_pdf(autor, output_dir1)

print("Baixando PDFs de Leis co-autorais...")
output_dir2 = "./content/co-autorais"
baixar_pdf(coautores, output_dir2)
